version: "2"
services:
    nginx:
        image: nginx:latest
        container_name: www
        mem_limit: 256m
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        image: overbid/nginx-php-oci8-redis:latest
        container_name: phpfpm
        mem_limit: 256m
        volumes:
            - ./code:/code
        depends_on:
            - redis
    redis:
        image: redis:latest
        container_name: cache
        mem_limit: 256m