version: "2"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        mem_limit: 256m
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build: ./php
        container_name: php
        mem_limit: 256m
        volumes:
            - ./code:/code
        depends_on:
            - redis
    redis:
        image: redis:latest
        container_name: redis
        mem_limit: 256m